/* query is to tell dbs to give exactly what piece of information you wanna collect from dbs
DECIMAL (10,4) MEANS TOTAL A NUMBER WILL CONSIST OF 10 DIGIT IN WHICH 4 WILL BE AFTER THE DECIMAL POINT(.) AND 6 BEFORE IT.
INT --> FOR WHOLE NO.
VARCHAR(20) --> FOR STRING CONTAINING AT MOST 20 CHAR VARIABLES
DATE --> FOR "DD-MM-YY"  FORMAT
TIMESTAMP --> FOR "DD-MM-YY" AND "HH:MM:SS" FORMAT */
CREATE TABLE STUDENT1(
STUDENT_ID INT PRIMARY KEY,
NAME VARCHAR(20),
PROFFF VARCHAR(20) 
);
/* or can be also be written as */
CREATE TABLE STUDENT2(
STUDENT_ID INT,
NAME VARCHAR(20),
PROFFF VARCHAR(20),
PRIMARY KEY(STUDENT_ID)
);
DESCRIBE STUDENT2;
DROP TABLE STUDENT2;
ALTER TABLE STUDENT2 ADD SGPA DECIMAL(2,2); /*TO ADD COLUMS OR ATTRIBUTE*/
ALTER TABLE STUDENT2 DROP COLUMN SGPA; /*TO DROP ATTRIBUTE*/

--NOW TO INSERT DATA 
CREATE TABLE STUDENTS(
STUDENT_ID INT PRIMARY KEY,   #primary key is both unique and not null
NAME VARCHAR(20),
PROFFF VARCHAR(20)    #here unique indicates profff attribute to be unique , and redundancy should be there 
);
SELECT * FROM STUDENTS;    -- SELECT * MEANS COLLECT ALL THE INFO 
INSERT INTO STUDENTS VALUE(1,'ABHI','THINK TANK');
INSERT INTO STUDENTS(STUDENT_ID,NAME) VALUE(2,'JAISHANKAR'); --ANOTHER WAY TO INSERT DATA
INSERT INTO STUDENTS VALUE(5,'DEEPA','COOK');
INSERT INTO STUDENTS VALUE(4,'CHRIS','ACTOR');
UPDATE STUDENTS 
SET PROFFF ='CHEF'
WHERE PROFFF='COOK';  --TO UPDATE ROW VALUES
UPDATE STUDENTS 
SET NAME ='Ms. SHARMA'. PROFFF='EDITOR AND ANCHOR'
WHERE STUDENT_ID=3;  --THUS WE CAN UPDATE MULTIPLE COLUMN WITHIN ONE QUERY
DELETE FROM STUDENTS 
WHERE STUDENT_ID=4; --DELETION OF ROW
--HERE NAME CAN  ALSO BE SPECIFIED AS STUDENTS.NAME
SELECT NAME,PROFFF  
FROM STUDENTS
ORDER BY STUDENT_ID DESC;  --TO DISPLAY DATA IN DESCENDING ORDER
SELECT NAME 
FROM STUDENT 
ORDER BY STUDENT_ID ASC
LIMIT 3;      --TO LIMIT THE DISPLAY 
SELECT PROFFF,NAME
FROM STUDENTS
WHERE PROFFF="CHEF" OR NAME='ABHI';
SELECT PROFFF
FROM STUDENTS
WHERE PROFFF <> 'TECHNOCRAT' AND STUDENT_ID<=4; --HERE <> MEANS !- (NOT EQUL TO) 
SELECT *
FROM STUDENTS
WHERE NAME IN ('ABHI','DEEPA') AND STUDENT_ID >2;   --ANOTHER WAY TO SELECT THESE GROUP OF VAKUES
drop table students;
